name: build-and-run-tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # build project
    - name: CMake
      working-directory: ${{ github.workspace }}/build
      run: cmake ..
    - name: Make
      working-directory: ${{ github.workspace }}/build
      run: make
    # run tests
    - name: Tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -V